name             'mediawiki'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mediawiki'
long_description 'Installs/Configures mediawiki'
version          '0.1.0'
depends          'mysql'
depends          'database'
depends          'nginx'
