name 'mediawiki'
maintainer 'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license 'All rights reserved'
description 'Installs/Configures mediawiki'
long_description 'Installs/Configures mediawiki'
version '0.1.0'
depends 'mysql'
depends 'database'
depends 'apache2'
depends 'php'
supports 'centos', '>=6'
supports 'rhel', '>=6'
